CREATE NONCLUSTERED INDEX [IX_IQ_NIELSEN_SQAD_IQ_CC_Key] ON [dbo].[IQ_NIELSEN_SQAD] 
(
	[IQ_CC_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO