CREATE NONCLUSTERED INDEX [IX_IQ_Nielsen_Averages] ON [dbo].[IQ_Nielsen_Averages] 
(
	[Affil_IQ_CC_Key] ASC,
	[IQ_Start_Point] ASC
)
INCLUDE ( [Avg_Ratings_Pt],
[DAYPARTID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

