CREATE NONCLUSTERED INDEX [IX1_IQTWITTER] ON [dbo].[IQAgent_TwitterResults] 
(
	[IQAgentSearchRequestID] ASC,
	[TweetID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 70) ON [PRIMARY]
GO
