CREATE NONCLUSTERED INDEX [idx_IQCore_Recording_IQCore_Recording__3more] ON [dbo].[IQCore_Recording] 
(
	[_SourceGuid] ASC
)
INCLUDE ( [ID],
[StartDate],
[EndDate]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


