//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMediaGroup.ExposeApi.Domain
{
    public partial class Dma
    {
        #region Primitive Properties
    
        public string Name
        {
            get;
            set;
        }
    
        public string Num
        {
            get;
            set;
        }

        #endregion
    }
}
