//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMediaGroup.ExposeApi.Domain
{
    public partial class PMGSearchLog
    {
        #region Primitive Properties
    
        public virtual long PMGSearchLogKey
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CustomerID
        {
            get;
            set;
        }
    
        public virtual string SearchType
        {
            get;
            set;
        }
    
        public virtual string RequestXML
        {
            get;
            set;
        }
    
        public virtual string ErrorResponseXML
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ModifiedDate
        {
            get;
            set;
        }
    
        public virtual string CreatedBy
        {
            get;
            set;
        }
    
        public virtual string ModifiedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsActive
        {
            get;
            set;
        }

        #endregion
    }
}
