//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMediaGroup.CoreServices.Domain
{
    public partial class IQ_Five_Min_Staging
    {
        #region Primitive Properties
    
        public virtual long IQ_FiveMS_Key
        {
            get;
            set;
        }
    
        public virtual string IQ_CC_Key
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> Media_Recordfile_GUID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Last_Media_Segment
        {
            get;
            set;
        }
    
        public virtual string Current_Active_Media_File
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> CCTxt_Recordfile_GUID
        {
            get;
            set;
        }
    
        public virtual string Media_Process_Status
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Last_CCTxt_Segment
        {
            get;
            set;
        }
    
        public virtual string Current_Active_CCTxt_File
        {
            get;
            set;
        }
    
        public virtual string CC_Process_Status
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ModifiedDate
        {
            get;
            set;
        }

        #endregion
    }
}
