//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMediaGroup.CoreServices.Domain
{
    public partial class RootPath
    {
        #region Primitive Properties
    
        public int id
        {
            get;
            set;
        }
    
        public Nullable<bool> isActive
        {
            get;
            set;
        }
    
        public int rootPathTypeID
        {
            get;
            set;
        }
    
        public string storagePath
        {
            get;
            set;
        }

        #endregion
    }
}
