//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMediaGroup.Domain
{
    public partial class AdvancedSearchServiceState
    {
        #region Primitive Properties
    
        public virtual long AdvancedSearchServiceStateKey
        {
            get;
            set;
        }
    
        public virtual string SearchCriteria
        {
            get;
            set;
        }
    
        public virtual string SessionID
        {
            get;
            set;
        }
    
        public virtual int SSPPageNo
        {
            get;
            set;
        }
    
        public virtual int PMGPageNo
        {
            get;
            set;
        }
    
        public virtual int PageNo
        {
            get;
            set;
        }
    
        public virtual System.DateTime RequestedDate
        {
            get;
            set;
        }
    
        public virtual bool IsSamePMGPage
        {
            get;
            set;
        }
    
        public virtual int PMGPageEndIndex
        {
            get;
            set;
        }
    
        public virtual string IQCCKeyServed
        {
            get;
            set;
        }

        #endregion
    }
}
