//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMediaGroup.Domain
{
    public partial class ArchiveClipService
    {
        #region Primitive Properties
    
        public string ClipTitle
        {
            get;
            set;
        }
    
        public int ArchiveClipKey
        {
            get;
            set;
        }
    
        public string ThumbnailImagePath
        {
            get;
            set;
        }

        #endregion
    }
}
