//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMediaGroup.Domain
{
    public partial class IQService_UGCRawClipExport
    {
        #region Primitive Properties
    
        public virtual long ID
        {
            get;
            set;
        }
    
        public virtual System.Guid ClipGUID
        {
            get;
            set;
        }
    
        public virtual string Status
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateQueued
        {
            get;
            set;
        }
    
        public virtual System.DateTime LastModified
        {
            get;
            set;
        }
    
        public virtual string OutputPath
        {
            get;
            set;
        }

        #endregion
    }
}
