//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMediaGroup.Domain
{
    public partial class NielsenData
    {
        #region Primitive Properties
    
        public string IQ_CC_Key
        {
            get;
            set;
        }
    
        public System.Guid Guid
        {
            get;
            set;
        }
    
        public string SQAD_SHAREVALUE
        {
            get;
            set;
        }
    
        public Nullable<int> AUDIENCE
        {
            get;
            set;
        }

        #endregion
    }
}
