//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMediaGroup.Domain
{
    public partial class PlayerClipData
    {
        #region Primitive Properties
    
        public string IQ_Dma_Name
        {
            get;
            set;
        }
    
        public string Title120
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> IQ_Local_Air_Date
        {
            get;
            set;
        }
    
        public string StationID
        {
            get;
            set;
        }
    
        public string IQ_Dma_Num
        {
            get;
            set;
        }

        #endregion
    }
}
