ALTER TABLE [dbo].[Client]
    ADD CONSTRAINT [IX_Client] UNIQUE NONCLUSTERED ([ClientGUID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

