ALTER TABLE [dbo].[AdvancedSearchServiceState]
    ADD CONSTRAINT [PK_AdvancedSearchServiceState] PRIMARY KEY CLUSTERED ([AdvancedSearchServiceStateKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

