ALTER TABLE [dbo].[BillFrequency]
    ADD CONSTRAINT [PK_BillFrequency] PRIMARY KEY CLUSTERED ([BillFrequencyKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

