ALTER TABLE [dbo].[CustomCategory]
    ADD CONSTRAINT [PK_CustomCategory] PRIMARY KEY CLUSTERED ([CategoryKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

