ALTER TABLE [dbo].[ClientRole]
    ADD CONSTRAINT [PK_ClientRole] PRIMARY KEY CLUSTERED ([ClientRoleKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

