ALTER TABLE [dbo].[IQCore_Clip]
    ADD CONSTRAINT [PK_IQCore_Clip] PRIMARY KEY CLUSTERED ([Guid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

