ALTER TABLE [dbo].[IQCore_NM]
    ADD CONSTRAINT [PK_IQCore_Nm] PRIMARY KEY CLUSTERED ([ArticleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

