ALTER TABLE [dbo].[IQRootpath_Location]
    ADD CONSTRAINT [PK_IQRootpath_Location] PRIMARY KEY CLUSTERED ([IQRpLocKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

