ALTER TABLE [dbo].[IQCore_ClipMeta]
    ADD CONSTRAINT [PK_IQCore_ClipMeta] PRIMARY KEY CLUSTERED ([_ClipGuid] ASC, [Field] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

