ALTER TABLE [dbo].[IQClient_CustomSettings]
    ADD CONSTRAINT [PK_IQClient_CustomSettings] PRIMARY KEY CLUSTERED ([_ClientGuid] ASC, [Field] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

