ALTER TABLE [dbo].[IQAgentResults]
    ADD CONSTRAINT [PK_IQAgentResults] PRIMARY KEY CLUSTERED ([IQAgentResultKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

