ALTER TABLE [dbo].[IQ_Five_Min_Staging] ADD  CONSTRAINT [PK_IQ_FiveMS] PRIMARY KEY CLUSTERED 
(
	[IQ_FiveMS_Key] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO