ALTER TABLE [dbo].[Iq_Service_log]
    ADD CONSTRAINT [PK_Iq_Service_log] PRIMARY KEY CLUSTERED ([Iq_Service_logKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

