ALTER TABLE [dbo].[Industry]
    ADD CONSTRAINT [PK_Industry] PRIMARY KEY CLUSTERED ([IndustryKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

