ALTER TABLE [dbo].[IQCore_AssetLocation]
    ADD CONSTRAINT [PK_IQCore_AssetLocation] PRIMARY KEY CLUSTERED ([_AssetGuid] ASC, [_AssetTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

