ALTER TABLE [dbo].[IQMediaGroupException]
    ADD CONSTRAINT [PK_IQMediaGroupException] PRIMARY KEY CLUSTERED ([IQMediaGroupExceptionKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

