ALTER TABLE [dbo].[IQClient_UGCMap]
    ADD CONSTRAINT [PK_IQClient_UGCMap] PRIMARY KEY CLUSTERED ([IQClient_UGCMapKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

