ALTER TABLE [dbo].[IQClient_CustomSettings_old]
    ADD CONSTRAINT [PK_IQCustom_Client] PRIMARY KEY CLUSTERED ([IQCustom_ClientID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

