ALTER TABLE [dbo].[IQNotificationSettings]
    ADD CONSTRAINT [PK_IQNotificationSettings] PRIMARY KEY CLUSTERED 
(
	[IQNotificationKey] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

