ALTER TABLE [dbo].[InboundReporting]
    ADD CONSTRAINT [PK_InboundReporting] PRIMARY KEY CLUSTERED ([InboundReportingKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

