ALTER TABLE [dbo].[MediaCategory]
    ADD CONSTRAINT [PK_MediaCategory] PRIMARY KEY CLUSTERED ([MediaCategoryKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

