ALTER TABLE [dbo].[OutboundReporting]
    ADD CONSTRAINT [PK_OutboundReporting] PRIMARY KEY CLUSTERED ([OutboundReportingKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

