ALTER TABLE [dbo].[PricingCode]
    ADD CONSTRAINT [PK_PricingCode] PRIMARY KEY CLUSTERED ([PricingCodeKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

