ALTER TABLE [dbo].[PromotionalVideo]
    ADD CONSTRAINT [PK_PromotionalVideo] PRIMARY KEY CLUSTERED ([PromotionalVideoKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

