ALTER TABLE [dbo].[RL_Station_exception]
    ADD CONSTRAINT [PK_RL_Station_exception] PRIMARY KEY CLUSTERED ([RL_Station_exceptionKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

