ALTER TABLE [dbo].[RL_CC_TEXT1]
    ADD CONSTRAINT [PK_RL_CC_TEXT1] PRIMARY KEY CLUSTERED ([RL_CC_TEXTKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

