ALTER TABLE [dbo].[RL_GUIDS2]
    ADD CONSTRAINT [PK_RL_GUIDS2] PRIMARY KEY CLUSTERED ([RL_GUIDSKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

