ALTER TABLE [dbo].[SSP_IQ_Cat]
    ADD CONSTRAINT [PK_SSP_IQ_Cat] PRIMARY KEY CLUSTERED ([SSP_IQ_CatKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

