ALTER TABLE [dbo].[SSP_Station_Affil]
    ADD CONSTRAINT [PK_SSP_Station_Affil] PRIMARY KEY CLUSTERED ([SSP_Station_AffilKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

