ALTER TABLE [dbo].[STATSKEDPROG]
    ADD CONSTRAINT [PK_STATSKEDPROG] PRIMARY KEY CLUSTERED ([StatSkedProgKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

