ALTER TABLE [dbo].[State]
    ADD CONSTRAINT [PK_State] PRIMARY KEY CLUSTERED ([StateKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

