ALTER TABLE [dbo].[TypeValue]
    ADD CONSTRAINT [PK_TypeValue] PRIMARY KEY CLUSTERED ([TypeValueKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

