ALTER TABLE [dbo].[UGC_Upload_Log]
    ADD CONSTRAINT [PK_UGC_upload_log] PRIMARY KEY CLUSTERED ([UGC_Upload_LogKey] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

