CREATE TABLE [dbo].[ArchiveNM](
	[ArchiveNMKey] [bigint] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
	[Keywords] [varchar](2048) NULL,
	[Description] [varchar](2048) NULL,
	[FirstName] [varchar](150) NULL,
	[LastName] [varchar](150) NULL,
	[CustomerGuid] [uniqueidentifier] NOT NULL,
	[ClientGuid] [uniqueidentifier] NOT NULL,
	[CategoryGuid] [uniqueidentifier] NOT NULL,
	[SubCategory1Guid] [uniqueidentifier] NULL,
	[SubCategory2Guid] [uniqueidentifier] NULL,
	[SubCategory3Guid] [uniqueidentifier] NULL,
	[ArticleID] [varchar](50) NOT NULL,
	[ArticleContent] [nvarchar](max) NULL,
	[Url] [varchar](500) NULL,
	[Harvest_Time] [datetime] NULL,
	[CompeteURL] [varchar](255) NULL,
	[Publication] [varchar](255) NULL,
	[Rating] [tinyint] NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[HighlightingText] [varchar](max) NULL,
	[Compete_Audience] [int] NULL,
	[IQAdShareValue] [decimal](18, 2) NULL,
	[Compete_Result] [varchar](1) NULL,
	[PositiveSentiment] [tinyint] NULL,
	[NegativeSentiment] [tinyint] NULL,
	[IQLicense] [tinyint] NULL,
	[v5SubMediaType] [varchar](50) NULL
) ON [PRIMARY]