CREATE TABLE [dbo].[IQ_MediaTypes_REORG]
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MediaType] [varchar](2) NOT NULL,
	[SubMediaType] [varchar](50) NULL,
	[DisplayName] [varchar](200) NULL,
	[_RoleKey] [bigint] NOT NULL,
	[_ParentRoleKey] [bigint] NOT NULL,
	[TypeLevel] [tinyint] NOT NULL,
	[HasSubMediaTypes] [bit] NOT NULL,
	[DataModelType] [varchar](2) NULL,
	[AnalyticsDataType] [varchar](20) NULL,
	[DiscChartSearchMethod] [varchar](200) NULL,
	[DiscResultsSearchMethod] [varchar](200) NULL,
	[DiscRptGenSearchMethod] [varchar](200) NULL,
	[FeedsResultView] [varchar](50) NULL,
	[FeedsChildResultView] [varchar](50) NULL,
	[DiscoveryResultView] [varchar](50) NULL,
	[MediaIconPath] [varchar](100) NULL,
	[UseAudience] [bit] NOT NULL,
	[UseMediaValue] [bit] NOT NULL,
	[SortOrder] [smallint] NULL,
	[IsActiveDiscovery] [bit] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[RequireNielsenAccess] [bit] NOT NULL,
	[RequireCompeteAccess] [bit] NOT NULL,
	[DashboardData] [varchar](2048) NULL,
	[UseHighlightingText] [bit] NOT NULL,
	[v4MediaType] [varchar](2) NULL,
	[v4SubMediaType] [varchar](50) NULL,
	[AgentNodeName] [varchar](50) NULL,
	[SourceTypes] [varchar](200) NULL,
	[AgentType] [smallint] NULL
)
