CREATE TABLE [dbo].[IQAgent_EarnedPaidHourSummary](
	[ID] [bigint] NOT NULL,
	[_ClientGuid] [uniqueidentifier] NOT NULL,
	[HourDateTime] [smalldatetime] NOT NULL,
	[_SearchRequestID] [bigint] NULL,
	[Market] [varchar](150) NULL,
	[Station] [varchar](150) NULL,
	[CountryNumber] [smallint] NULL,
	[NumberOfDocs] [int] NULL,
	[NumberOfHits] [bigint] NULL,
	[AM18_20] [bigint] NULL,
	[AM21_24] [bigint] NULL,
	[AM25_34] [bigint] NULL,
	[AM35_49] [bigint] NULL,
	[AM50_54] [bigint] NULL,
	[AM55_64] [bigint] NULL,
	[AM65_Plus] [bigint] NULL,
	[AF18_20] [bigint] NULL,
	[AF21_24] [bigint] NULL,
	[AF25_34] [bigint] NULL,
	[AF35_49] [bigint] NULL,
	[AF50_54] [bigint] NULL,
	[AF55_64] [bigint] NULL,
	[AF65_Plus] [bigint] NULL,
	[TotalAudience] [bigint] NULL,
	[PositiveSentiment] [int] NULL,
	[NegativeSentiment] [int] NULL,
	[IQAdShareValue] [float] NULL,
	[Seen_Earned] [int] NULL,
	[Seen_Paid] [int] NULL,
	[Heard_Earned] [int] NULL,
	[Heard_Paid] [int] NULL
) ON [PRIMARY]

GO
