CREATE TABLE [dbo].[IQAgent_EarnedPaidDaySummary](
	[ID] [bigint] NOT NULL,
	[_ClientGuid] [uniqueidentifier] NOT NULL,
	[DayDate] [date] NOT NULL,
	[_SearchRequestID] [bigint] NULL,
	[Market] [varchar](150) NULL,
	[Station] [varchar](150) NULL,
	[CountryNumber] [smallint] NULL,
	[NumberOfDocs] [int] NULL,
	[NumberOfHits] [bigint] NULL,
	[AM18_20] [bigint] NULL,
	[AM21_24] [bigint] NULL,
	[AM25_34] [bigint] NULL,
	[AM35_49] [bigint] NULL,
	[AM50_54] [bigint] NULL,
	[AM55_64] [bigint] NULL,
	[AM65_Plus] [bigint] NULL,
	[AF18_20] [bigint] NULL,
	[AF21_24] [bigint] NULL,
	[AF25_34] [bigint] NULL,
	[AF35_49] [bigint] NULL,
	[AF50_54] [bigint] NULL,
	[AF55_64] [bigint] NULL,
	[AF65_Plus] [bigint] NULL,
	[TotalAudience] [bigint] NULL,
	[PositiveSentiment] [int] NULL,
	[NegativeSentiment] [int] NULL,
	[IQAdShareValue] [float] NULL,
	[Seen_Earned] [int] NULL,
	[Seen_Paid] [int] NULL,
	[Heard_Earned] [int] NULL,
	[Heard_Paid] [int] NULL,
	[LastUpdated] [datetime] NULL,
	[UnProcessed] [int] NULL,
	[LtNumberOfDocs] [int] NULL,
	[LtNumberOfHits] [bigint] NULL,
	[LtAM18_20] [bigint] NULL,
	[LtAM21_24] [bigint] NULL,
	[LtAM24_34] [bigint] NULL,
	[LtAM35_49] [bigint] NULL,
	[LtAM50_54] [bigint] NULL,
	[LtAM55_64] [bigint] NULL,
	[LtAM65_Plus] [bigint] NULL,
	[LtAF18_20] [bigint] NULL,
	[LtAF21_24] [bigint] NULL,
	[LtAF25_34] [bigint] NULL,
	[LtAF35_49] [bigint] NULL,
	[LtAF50_54] [bigint] NULL,
	[LtAF55_64] [bigint] NULL,
	[LtAF65_Plus] [bigint] NULL,
	[LtTotalAudience] [bigint] NULL,
	[LtPositiveSentiment] [int] NULL,
	[LtNegativeSentiment] [int] NULL,
	[LtIQAdShareValue] [float] NULL,
	[LtSeen_Earned] [int] NULL,
	[LtSeen_Paid] [int] NULL,
	[LtHeard_Earned] [int] NULL,
	[LtHeard_Paid] [int] NULL
) ON [PRIMARY]

GO


