CREATE TABLE [dbo].[IQAgent_TwitterResults](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[IQAgentSearchRequestID] [bigint] NOT NULL,
	[_QueryVersion] [int] NULL,
	[TweetID] [varchar](50) NOT NULL,
	[actor_followersCount] [int] NULL,
	[actor_friendsCount] [int] NULL,
	[Summary] [varchar](max) NULL,
	[tweet_posteddatetime] [datetime] NOT NULL,
	[actor_image] [varchar](max) NULL,
	[actor_link] [varchar](max) NULL,
	[actor_displayname] [nvarchar](50) NULL,
	[actor_preferredname] [nvarchar](50) NULL,
	[gnip_klout_score] [smallint] NULL,
	[Number_Hits] [int] NULL,
	[HighlightingText] [xml] NULL,
	[Sentiment] [xml] NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[i_comm_flag] [bit] NULL,
	[h_comm_flag] [bit] NULL,
	[d_comm_flag] [bit] NULL,
	[w_comm_flag] [bit] NULL,
	[v5SubMediaType] [varchar](50) NULL
) ON [PRIMARY]