//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMedia.Domain.NM
{
    public partial class RootPath
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Comment
        {
            get;
            set;
        }
    
        public virtual string StoragePath
        {
            get;
            set;
        }
    
        public virtual string StreamSuffixPath
        {
            get;
            set;
        }
    
        public virtual string AppName
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual int RootPathTypeID
        {
            get { return _rootPathTypeID; }
            set
            {
                if (_rootPathTypeID != value)
                {
                    if (RootPathType != null && RootPathType.ID != value)
                    {
                        RootPathType = null;
                    }
                    _rootPathTypeID = value;
                }
            }
        }
        private int _rootPathTypeID;

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<NM> NMs
        {
            get
            {
                if (_nMs == null)
                {
                    var newCollection = new FixupCollection<NM>();
                    newCollection.CollectionChanged += FixupNMs;
                    _nMs = newCollection;
                }
                return _nMs;
            }
            set
            {
                if (!ReferenceEquals(_nMs, value))
                {
                    var previousValue = _nMs as FixupCollection<NM>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupNMs;
                    }
                    _nMs = value;
                    var newValue = value as FixupCollection<NM>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupNMs;
                    }
                }
            }
        }
        private ICollection<NM> _nMs;
    
        public virtual RootPathType RootPathType
        {
            get { return _rootPathType; }
            set
            {
                if (!ReferenceEquals(_rootPathType, value))
                {
                    var previousValue = _rootPathType;
                    _rootPathType = value;
                    FixupRootPathType(previousValue);
                }
            }
        }
        private RootPathType _rootPathType;

        #endregion
        #region Association Fixup
    
        private void FixupRootPathType(RootPathType previousValue)
        {
            if (previousValue != null && previousValue.RootPaths.Contains(this))
            {
                previousValue.RootPaths.Remove(this);
            }
    
            if (RootPathType != null)
            {
                if (!RootPathType.RootPaths.Contains(this))
                {
                    RootPathType.RootPaths.Add(this);
                }
                if (RootPathTypeID != RootPathType.ID)
                {
                    RootPathTypeID = RootPathType.ID;
                }
            }
        }
    
        private void FixupNMs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (NM item in e.NewItems)
                {
                    item.RootPath = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (NM item in e.OldItems)
                {
                    if (ReferenceEquals(item.RootPath, this))
                    {
                        item.RootPath = null;
                    }
                }
            }
        }

        #endregion
    }
}
