//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDownload")]
public interface IDownload
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownload/WakeupService", ReplyAction="http://tempuri.org/IDownload/WakeupServiceResponse")]
    void WakeupService();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDownloadChannel : IDownload, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DownloadClient : System.ServiceModel.ClientBase<IDownload>, IDownload
{
    
    public DownloadClient()
    {
    }
    
    public DownloadClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DownloadClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DownloadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DownloadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void WakeupService()
    {
        base.Channel.WakeupService();
    }
}
