//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("iqmediagroupModel", "FK_IQCore_RootPath_IQCore_RootPathType", "IQCore_RootPathType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IQMedia.Domain.SM.RootPathType), "IQCore_RootPath", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IQMedia.Domain.SM.RootPath), true)]
[assembly: EdmRelationshipAttribute("iqmediagroupModel", "FK_IQCore_Sm_IQCore_RootPath", "IQCore_RootPath", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(IQMedia.Domain.SM.RootPath), "IQCore_SM", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IQMedia.Domain.SM.SM), true)]

#endregion

namespace IQMedia.Domain.SM
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IQMediaGroupEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IQMediaGroupEntities object using the connection string found in the 'IQMediaGroupEntities' section of the application configuration file.
        /// </summary>
        public IQMediaGroupEntities() : base("name=IQMediaGroupEntities", "IQMediaGroupEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IQMediaGroupEntities object.
        /// </summary>
        public IQMediaGroupEntities(string connectionString) : base(connectionString, "IQMediaGroupEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IQMediaGroupEntities object.
        /// </summary>
        public IQMediaGroupEntities(EntityConnection connection) : base(connection, "IQMediaGroupEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RootPath> RootPaths
        {
            get
            {
                if ((_RootPaths == null))
                {
                    _RootPaths = base.CreateObjectSet<RootPath>("RootPaths");
                }
                return _RootPaths;
            }
        }
        private ObjectSet<RootPath> _RootPaths;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RootPathType> RootPathTypes
        {
            get
            {
                if ((_RootPathTypes == null))
                {
                    _RootPathTypes = base.CreateObjectSet<RootPathType>("RootPathTypes");
                }
                return _RootPathTypes;
            }
        }
        private ObjectSet<RootPathType> _RootPathTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SM> SMs
        {
            get
            {
                if ((_SMs == null))
                {
                    _SMs = base.CreateObjectSet<SM>("SMs");
                }
                return _SMs;
            }
        }
        private ObjectSet<SM> _SMs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RootPaths EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRootPaths(RootPath rootPath)
        {
            base.AddObject("RootPaths", rootPath);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RootPathTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRootPathTypes(RootPathType rootPathType)
        {
            base.AddObject("RootPathTypes", rootPathType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SMs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSMs(SM sM)
        {
            base.AddObject("SMs", sM);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iqmediagroupModel", Name="RootPath")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RootPath : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RootPath object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="comment">Initial value of the Comment property.</param>
        /// <param name="storagePath">Initial value of the StoragePath property.</param>
        /// <param name="streamSuffixPath">Initial value of the StreamSuffixPath property.</param>
        /// <param name="appName">Initial value of the AppName property.</param>
        /// <param name="c_RootPathTypeID">Initial value of the C_RootPathTypeID property.</param>
        public static RootPath CreateRootPath(global::System.Int32 id, global::System.String comment, global::System.String storagePath, global::System.String streamSuffixPath, global::System.String appName, global::System.Int32 c_RootPathTypeID)
        {
            RootPath rootPath = new RootPath();
            rootPath.ID = id;
            rootPath.Comment = comment;
            rootPath.StoragePath = storagePath;
            rootPath.StreamSuffixPath = streamSuffixPath;
            rootPath.AppName = appName;
            rootPath.C_RootPathTypeID = c_RootPathTypeID;
            return rootPath;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StoragePath
        {
            get
            {
                return _StoragePath;
            }
            set
            {
                OnStoragePathChanging(value);
                ReportPropertyChanging("StoragePath");
                _StoragePath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StoragePath");
                OnStoragePathChanged();
            }
        }
        private global::System.String _StoragePath;
        partial void OnStoragePathChanging(global::System.String value);
        partial void OnStoragePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StreamSuffixPath
        {
            get
            {
                return _StreamSuffixPath;
            }
            set
            {
                OnStreamSuffixPathChanging(value);
                ReportPropertyChanging("StreamSuffixPath");
                _StreamSuffixPath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StreamSuffixPath");
                OnStreamSuffixPathChanged();
            }
        }
        private global::System.String _StreamSuffixPath;
        partial void OnStreamSuffixPathChanging(global::System.String value);
        partial void OnStreamSuffixPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AppName
        {
            get
            {
                return _AppName;
            }
            set
            {
                OnAppNameChanging(value);
                ReportPropertyChanging("AppName");
                _AppName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AppName");
                OnAppNameChanged();
            }
        }
        private global::System.String _AppName;
        partial void OnAppNameChanging(global::System.String value);
        partial void OnAppNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_RootPathTypeID
        {
            get
            {
                return _C_RootPathTypeID;
            }
            set
            {
                OnC_RootPathTypeIDChanging(value);
                ReportPropertyChanging("C_RootPathTypeID");
                _C_RootPathTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_RootPathTypeID");
                OnC_RootPathTypeIDChanged();
            }
        }
        private global::System.Int32 _C_RootPathTypeID;
        partial void OnC_RootPathTypeIDChanging(global::System.Int32 value);
        partial void OnC_RootPathTypeIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iqmediagroupModel", "FK_IQCore_RootPath_IQCore_RootPathType", "IQCore_RootPathType")]
        public RootPathType RootPathType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RootPathType>("iqmediagroupModel.FK_IQCore_RootPath_IQCore_RootPathType", "IQCore_RootPathType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RootPathType>("iqmediagroupModel.FK_IQCore_RootPath_IQCore_RootPathType", "IQCore_RootPathType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RootPathType> RootPathTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RootPathType>("iqmediagroupModel.FK_IQCore_RootPath_IQCore_RootPathType", "IQCore_RootPathType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RootPathType>("iqmediagroupModel.FK_IQCore_RootPath_IQCore_RootPathType", "IQCore_RootPathType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iqmediagroupModel", "FK_IQCore_Sm_IQCore_RootPath", "IQCore_SM")]
        public EntityCollection<SM> SMs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SM>("iqmediagroupModel.FK_IQCore_Sm_IQCore_RootPath", "IQCore_SM");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SM>("iqmediagroupModel.FK_IQCore_Sm_IQCore_RootPath", "IQCore_SM", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iqmediagroupModel", Name="RootPathType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RootPathType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RootPathType object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static RootPathType CreateRootPathType(global::System.Int32 id, global::System.String name, global::System.String description)
        {
            RootPathType rootPathType = new RootPathType();
            rootPathType.ID = id;
            rootPathType.Name = name;
            rootPathType.Description = description;
            return rootPathType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iqmediagroupModel", "FK_IQCore_RootPath_IQCore_RootPathType", "IQCore_RootPath")]
        public EntityCollection<RootPath> RootPaths
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RootPath>("iqmediagroupModel.FK_IQCore_RootPath_IQCore_RootPathType", "IQCore_RootPath");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RootPath>("iqmediagroupModel.FK_IQCore_RootPath_IQCore_RootPathType", "IQCore_RootPath", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="iqmediagroupModel", Name="SM")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SM : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SM object.
        /// </summary>
        /// <param name="articleID">Initial value of the ArticleID property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static SM CreateSM(global::System.String articleID, global::System.String status)
        {
            SM sM = new SM();
            sM.ArticleID = articleID;
            sM.Status = status;
            return sM;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ArticleID
        {
            get
            {
                return _ArticleID;
            }
            set
            {
                if (_ArticleID != value)
                {
                    OnArticleIDChanging(value);
                    ReportPropertyChanging("ArticleID");
                    _ArticleID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ArticleID");
                    OnArticleIDChanged();
                }
            }
        }
        private global::System.String _ArticleID;
        partial void OnArticleIDChanging(global::System.String value);
        partial void OnArticleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C_RootPathID
        {
            get
            {
                return _C_RootPathID;
            }
            set
            {
                OnC_RootPathIDChanging(value);
                ReportPropertyChanging("C_RootPathID");
                _C_RootPathID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_RootPathID");
                OnC_RootPathIDChanged();
            }
        }
        private Nullable<global::System.Int32> _C_RootPathID;
        partial void OnC_RootPathIDChanging(Nullable<global::System.Int32> value);
        partial void OnC_RootPathIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> harvest_time
        {
            get
            {
                return _harvest_time;
            }
            set
            {
                Onharvest_timeChanging(value);
                ReportPropertyChanging("harvest_time");
                _harvest_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("harvest_time");
                Onharvest_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _harvest_time;
        partial void Onharvest_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onharvest_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModified
        {
            get
            {
                return _LastModified;
            }
            set
            {
                OnLastModifiedChanging(value);
                ReportPropertyChanging("LastModified");
                _LastModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModified");
                OnLastModifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModified;
        partial void OnLastModifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("iqmediagroupModel", "FK_IQCore_Sm_IQCore_RootPath", "IQCore_RootPath")]
        public RootPath RootPath
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RootPath>("iqmediagroupModel.FK_IQCore_Sm_IQCore_RootPath", "IQCore_RootPath").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RootPath>("iqmediagroupModel.FK_IQCore_Sm_IQCore_RootPath", "IQCore_RootPath").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RootPath> RootPathReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RootPath>("iqmediagroupModel.FK_IQCore_Sm_IQCore_RootPath", "IQCore_RootPath");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RootPath>("iqmediagroupModel.FK_IQCore_Sm_IQCore_RootPath", "IQCore_RootPath", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
