//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace IQMediaGroup.ExportClip.Domain
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IQMediaGroupRemoteEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IQMediaGroupRemoteEntities object using the connection string found in the 'IQMediaGroupRemoteEntities' section of the application configuration file.
        /// </summary>
        public IQMediaGroupRemoteEntities() : base("name=IQMediaGroupRemoteEntities", "IQMediaGroupRemoteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IQMediaGroupRemoteEntities object.
        /// </summary>
        public IQMediaGroupRemoteEntities(string connectionString) : base(connectionString, "IQMediaGroupRemoteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IQMediaGroupRemoteEntities object.
        /// </summary>
        public IQMediaGroupRemoteEntities(EntityConnection connection) : base(connection, "IQMediaGroupRemoteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IQService_Export> IQService_Export
        {
            get
            {
                if ((_IQService_Export == null))
                {
                    _IQService_Export = base.CreateObjectSet<IQService_Export>("IQService_Export");
                }
                return _IQService_Export;
            }
        }
        private ObjectSet<IQService_Export> _IQService_Export;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IQService_Export EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIQService_Export(IQService_Export iQService_Export)
        {
            base.AddObject("IQService_Export", iQService_Export);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IQMediaGroupRemoteModel", Name="IQService_Export")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IQService_Export : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IQService_Export object.
        /// </summary>
        /// <param name="iQService_ExportKey">Initial value of the IQService_ExportKey property.</param>
        public static IQService_Export CreateIQService_Export(global::System.Int64 iQService_ExportKey)
        {
            IQService_Export iQService_Export = new IQService_Export();
            iQService_Export.IQService_ExportKey = iQService_ExportKey;
            return iQService_Export;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IQService_ExportKey
        {
            get
            {
                return _IQService_ExportKey;
            }
            set
            {
                if (_IQService_ExportKey != value)
                {
                    OnIQService_ExportKeyChanging(value);
                    ReportPropertyChanging("IQService_ExportKey");
                    _IQService_ExportKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IQService_ExportKey");
                    OnIQService_ExportKeyChanged();
                }
            }
        }
        private global::System.Int64 _IQService_ExportKey;
        partial void OnIQService_ExportKeyChanging(global::System.Int64 value);
        partial void OnIQService_ExportKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ClipGUID
        {
            get
            {
                return _ClipGUID;
            }
            set
            {
                OnClipGUIDChanging(value);
                ReportPropertyChanging("ClipGUID");
                _ClipGUID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClipGUID");
                OnClipGUIDChanged();
            }
        }
        private Nullable<global::System.Guid> _ClipGUID;
        partial void OnClipGUIDChanging(Nullable<global::System.Guid> value);
        partial void OnClipGUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClipRemoteLocation
        {
            get
            {
                return _ClipRemoteLocation;
            }
            set
            {
                OnClipRemoteLocationChanging(value);
                ReportPropertyChanging("ClipRemoteLocation");
                _ClipRemoteLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClipRemoteLocation");
                OnClipRemoteLocationChanged();
            }
        }
        private global::System.String _ClipRemoteLocation;
        partial void OnClipRemoteLocationChanging(global::System.String value);
        partial void OnClipRemoteLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClipInfo
        {
            get
            {
                return _ClipInfo;
            }
            set
            {
                OnClipInfoChanging(value);
                ReportPropertyChanging("ClipInfo");
                _ClipInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClipInfo");
                OnClipInfoChanged();
            }
        }
        private global::System.String _ClipInfo;
        partial void OnClipInfoChanging(global::System.String value);
        partial void OnClipInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateModified
        {
            get
            {
                return _DateModified;
            }
            set
            {
                OnDateModifiedChanging(value);
                ReportPropertyChanging("DateModified");
                _DateModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModified");
                OnDateModifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateModified;
        partial void OnDateModifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion
    
    }

    #endregion
    
}
