//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace IQMedia.Domain
{
    public partial class IQMediaGroupEntities : ObjectContext
    {
        public const string ConnectionString = "name=IQMediaGroupEntities";
        public const string ContainerName = "IQMediaGroupEntities";
    
        #region Constructors
    
        public IQMediaGroupEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public IQMediaGroupEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public IQMediaGroupEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Clip> Clips
        {
            get { return _clips  ?? (_clips = CreateObjectSet<Clip>("Clips")); }
        }
        private ObjectSet<Clip> _clips;
    
        public ObjectSet<ClipInfo> ClipInfo
        {
            get { return _clipInfo  ?? (_clipInfo = CreateObjectSet<ClipInfo>("ClipInfo")); }
        }
        private ObjectSet<ClipInfo> _clipInfo;
    
        public ObjectSet<ClipMeta> ClipMeta
        {
            get { return _clipMeta  ?? (_clipMeta = CreateObjectSet<ClipMeta>("ClipMeta")); }
        }
        private ObjectSet<ClipMeta> _clipMeta;
    
        public ObjectSet<Recordfile> Recordfiles
        {
            get { return _recordfiles  ?? (_recordfiles = CreateObjectSet<Recordfile>("Recordfiles")); }
        }
        private ObjectSet<Recordfile> _recordfiles;
    
        public ObjectSet<RecordfileType> RecordfileTypes
        {
            get { return _recordfileTypes  ?? (_recordfileTypes = CreateObjectSet<RecordfileType>("RecordfileTypes")); }
        }
        private ObjectSet<RecordfileType> _recordfileTypes;
    
        public ObjectSet<Recording> Recordings
        {
            get { return _recordings  ?? (_recordings = CreateObjectSet<Recording>("Recordings")); }
        }
        private ObjectSet<Recording> _recordings;
    
        public ObjectSet<RootPath> RootPaths
        {
            get { return _rootPaths  ?? (_rootPaths = CreateObjectSet<RootPath>("RootPaths")); }
        }
        private ObjectSet<RootPath> _rootPaths;
    
        public ObjectSet<RootPathType> RootPathTypes
        {
            get { return _rootPathTypes  ?? (_rootPathTypes = CreateObjectSet<RootPathType>("RootPathTypes")); }
        }
        private ObjectSet<RootPathType> _rootPathTypes;
    
        public ObjectSet<Source> Sources
        {
            get { return _sources  ?? (_sources = CreateObjectSet<Source>("Sources")); }
        }
        private ObjectSet<Source> _sources;
    
        public ObjectSet<Timezone> Timezones
        {
            get { return _timezones  ?? (_timezones = CreateObjectSet<Timezone>("Timezones")); }
        }
        private ObjectSet<Timezone> _timezones;
    
        public ObjectSet<ImpressionSummary> ImpressionSummary
        {
            get { return _impressionSummary  ?? (_impressionSummary = CreateObjectSet<ImpressionSummary>("ImpressionSummary")); }
        }
        private ObjectSet<ImpressionSummary> _impressionSummary;
    
        public ObjectSet<PlaySummary> PlaySummary
        {
            get { return _playSummary  ?? (_playSummary = CreateObjectSet<PlaySummary>("PlaySummary")); }
        }
        private ObjectSet<PlaySummary> _playSummary;
    
        public ObjectSet<AssetLocation> AssetLocations
        {
            get { return _assetLocations  ?? (_assetLocations = CreateObjectSet<AssetLocation>("AssetLocations")); }
        }
        private ObjectSet<AssetLocation> _assetLocations;
    
        public ObjectSet<AssetType> AssetTypes
        {
            get { return _assetTypes  ?? (_assetTypes = CreateObjectSet<AssetType>("AssetTypes")); }
        }
        private ObjectSet<AssetType> _assetTypes;
    
        public ObjectSet<PlayerMsgLog> PlayerMsgLogs
        {
            get { return _playerMsgLogs  ?? (_playerMsgLogs = CreateObjectSet<PlayerMsgLog>("PlayerMsgLogs")); }
        }
        private ObjectSet<PlayerMsgLog> _playerMsgLogs;
    
        public ObjectSet<PlayLog> PlayLogs
        {
            get { return _playLogs  ?? (_playLogs = CreateObjectSet<PlayLog>("PlayLogs")); }
        }
        private ObjectSet<PlayLog> _playLogs;
    
        public ObjectSet<Customer> Customers
        {
            get { return _customers  ?? (_customers = CreateObjectSet<Customer>("Customers")); }
        }
        private ObjectSet<Customer> _customers;
    
        public ObjectSet<LegacyCustomer> LegacyCustomers
        {
            get { return _legacyCustomers  ?? (_legacyCustomers = CreateObjectSet<LegacyCustomer>("LegacyCustomers")); }
        }
        private ObjectSet<LegacyCustomer> _legacyCustomers;

        #endregion
    }
}
