//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMedia.Domain
{
    public partial class Recording
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual System.Guid SourceGuid
        {
            get { return _sourceGuid; }
            set
            {
                if (_sourceGuid != value)
                {
                    if (Source != null && Source.Guid != value)
                    {
                        Source = null;
                    }
                    _sourceGuid = value;
                }
            }
        }
        private System.Guid _sourceGuid;
    
        public virtual System.DateTime StartDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime EndDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Recordfile> Recordfiles
        {
            get
            {
                if (_recordfiles == null)
                {
                    var newCollection = new FixupCollection<Recordfile>();
                    newCollection.CollectionChanged += FixupRecordfiles;
                    _recordfiles = newCollection;
                }
                return _recordfiles;
            }
            set
            {
                if (!ReferenceEquals(_recordfiles, value))
                {
                    var previousValue = _recordfiles as FixupCollection<Recordfile>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRecordfiles;
                    }
                    _recordfiles = value;
                    var newValue = value as FixupCollection<Recordfile>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRecordfiles;
                    }
                }
            }
        }
        private ICollection<Recordfile> _recordfiles;
    
        public virtual Source Source
        {
            get { return _source; }
            set
            {
                if (!ReferenceEquals(_source, value))
                {
                    var previousValue = _source;
                    _source = value;
                    FixupSource(previousValue);
                }
            }
        }
        private Source _source;

        #endregion
        #region Association Fixup
    
        private void FixupSource(Source previousValue)
        {
            if (previousValue != null && previousValue.Recordings.Contains(this))
            {
                previousValue.Recordings.Remove(this);
            }
    
            if (Source != null)
            {
                if (!Source.Recordings.Contains(this))
                {
                    Source.Recordings.Add(this);
                }
                if (SourceGuid != Source.Guid)
                {
                    SourceGuid = Source.Guid;
                }
            }
        }
    
        private void FixupRecordfiles(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Recordfile item in e.NewItems)
                {
                    item.Recording = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Recordfile item in e.OldItems)
                {
                    if (ReferenceEquals(item.Recording, this))
                    {
                        item.Recording = null;
                    }
                }
            }
        }

        #endregion
    }
}
