//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMedia.Domain
{
    public partial class RecordfileType
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual string Extension
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Recordfile> Recordfiles
        {
            get
            {
                if (_recordfiles == null)
                {
                    var newCollection = new FixupCollection<Recordfile>();
                    newCollection.CollectionChanged += FixupRecordfiles;
                    _recordfiles = newCollection;
                }
                return _recordfiles;
            }
            set
            {
                if (!ReferenceEquals(_recordfiles, value))
                {
                    var previousValue = _recordfiles as FixupCollection<Recordfile>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRecordfiles;
                    }
                    _recordfiles = value;
                    var newValue = value as FixupCollection<Recordfile>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRecordfiles;
                    }
                }
            }
        }
        private ICollection<Recordfile> _recordfiles;

        #endregion
        #region Association Fixup
    
        private void FixupRecordfiles(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Recordfile item in e.NewItems)
                {
                    item.RecordfileType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Recordfile item in e.OldItems)
                {
                    if (ReferenceEquals(item.RecordfileType, this))
                    {
                        item.RecordfileType = null;
                    }
                }
            }
        }

        #endregion
    }
}
